# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Java Build
    init: |
      cd java
      ./gradlew dependencies --refresh-dependencies
    command: |
      cd java
      gp sync-done java-build
      ./gradlew -t build
  - name: Java Server
    init: gp sync-await java-build
    command: |
      cd java
      ./gradlew bootRun
  
  - name: Angular
    init: |
      cd angular
      npm install
    command: |
      npm start

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8080
    onOpen: ignore
  - port: 4200
    onOpen: open-preview
