
image:
  file: .gitpod.Dockerfile

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: MySQL Server
    init: |
      gp await-port 3306
      mysql -e "create database testdb;"
      mysql -e "create user 'testuser'@'localhost' identified by 'testpassword';"
      mysql -e "grant all on testdb.* to 'testuser'@'localhost';"
      gp sync-done db-ready
  - name: Java Build
    init: |
      gp sync-await db-ready
      cd java
      ./gradlew dependencies --refresh-dependencies
    command: |
      gp sync-done java-build
      ./gradlew -t build
  - name: Java Server
    init: gp sync-await java-build
    command: |
      cd java
      ./gradlew bootRun

  - name: Angular
    init: |
      cd angular
      NG_CLI_ANALYTICS=ci npm install
    command: |
      npm start

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3306
    onOpen: ignore
  - port: 8080
    onOpen: ignore
  - port: 4200
    onOpen: open-preview

vscode:
  extensions:
    - eamodio.gitlens
    - pivotal.vscode-boot-dev-pack
    - angular.ng-template
    - cweijan.vscode-mysql-client2
